Feat/4 user info component
thelostcreatives/trq pull request #16
Opened 2023-08-23 21:51 UTC by Empairim

Take a look see for how it works

2023-08-23 23:23 UTC, xanderjakeq requested changes

2023-08-23 23:23 UTC, xanderjakeq commented on app/package.json
> +		"vscode": "^1.1.37"
i don't see the need for
- jwt-decode: we should get data from the server directly
- svelte-navigator: navigation is builtin for sveltekit
- svelte-quill: `<textarea/>` should be enough
- vscode: dunno what this is..

2023-08-23 23:23 UTC, xanderjakeq commented on app/src/lib/components/ItemList.svelte
> +<div class="bg-white shadow-md p-6 rounded-lg">
is this a duplicate?

2023-08-23 23:23 UTC, xanderjakeq commented on app/package.json
> +		"vscode": "^1.1.37"
we should probably use this https://www.npmjs.com/package/short-uuid
make prettier uuid with reasonable length

2023-08-23 23:23 UTC, xanderjakeq commented on app/src/lib/components/NewPageDialog.svelte
> +	let shortUuid = '';
initialize it here

2023-08-23 23:23 UTC, xanderjakeq commented on app/src/lib/components/NewPageDialog.svelte
> +	<h1 class="font-bold text-purple-500 text-lg mb-4">New Page</h1>
render the short `uuid` instead of "New Page"

2023-08-23 23:23 UTC, xanderjakeq commented on app/src/lib/components/ProfileCard.svelte
> +	onMount(async () => {
this component doesn't need any of this logic. should accept `data` and `update` function as props.

2023-08-23 23:23 UTC, xanderjakeq commented on app/src/lib/components/ProfileCard.svelte
> +<script>
use `<script lang="ts">`

2023-08-23 23:23 UTC, xanderjakeq commented on app/package-lock.json
use pnpm just for consistency, delete this file

2023-08-23 23:23 UTC, xanderjakeq commented on app/src/lib/components/ProfileCard.svelte
> +	onMount(async () => {
should be able to edit information and save

2023-08-23 23:23 UTC, Empairim commented on app/src/lib/components/NewPageDialog.svelte
Stuff

2023-08-23 23:25 UTC, Empairim commented on app/src/lib/components/ItemList.svelte
> +<div class="bg-white shadow-md p-6 rounded-lg">
ya I was just seeing how itd look with other components in place

2023-08-24 01:36 UTC, Empairim commented on app/package.json
> +		"vscode": "^1.1.37"
I 4got to remove those thought text editor should have bold italic ect but forgot about it xD

2023-08-25 05:11 UTC, xanderjakeq approved these changes
made changes, left component on home page for testing/viewing

2023-08-25 05:13 UTC, merged